spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/micro
    username: postgres
    password: Chufeng123
    
server:
   port: 8080 
   
eureka:
  client:
    service-url:
      defaultZone: https://eureka-sebas.herokuapp.com/eureka/ #http://localhost:8761/eureka/ 
      
#para seguridad      
#security:
 #  oauth2:
  #  resource:
   #   userInfoUri: http://localhost:9999/user     